Evr 505
everlytic/everlytic-woocommerce pull request #14
Opened 2020-09-02 07:48 UTC by ade1705

2020-09-03 18:17 UTC, thaboever requested changes

2020-09-03 18:17 UTC, thaboever commented on src/Events/AbandonedCart/EvCart.php
> +        return $this->evProducts->hydrateProductsForRequest($this->getProductIdsAndQuantity($cartItems));
hydrateProductsForRequest will return all products with status publish and those with the given ids as stated in include. This is a serious bug as users will get all products, including those that are not in their cart.

2020-09-04 09:45 UTC, ade1705 commented on src/Events/AbandonedCart/EvCart.php
> +        return $this->evProducts->hydrateProductsForRequest($this->getProductIdsAndQuantity($cartItems));
The method `getProductIdsAndQuantity` gets all the product IDs from the cart and return an array and then hydrate it using a whereIN to get all the products with that ID

2020-09-04 10:00 UTC, thaboever commented on src/Events/AbandonedCart/EvCart.php
> +        return $this->evProducts->hydrateProductsForRequest($this->getProductIdsAndQuantity($cartItems));
Check what happens when getProductIdsAndQuantity returns null. hydrateProductsForRequest will return all the products with status publish.

2020-09-10 11:57 UTC, thaboever approved these changes

2020-09-10 13:03 UTC, merged